sourcegraph/sourcegraph

- app/web_modules/sourcegraph/components/Header.js
- app/web_modules/sourcegraph/def/withDef.js
- app/web_modules/sourcegraph/repo/RepoActions.js
- app/web_modules/sourcegraph/repo/RepoBackend.js
- app/web_modules/sourcegraph/repo/RepoMain.js
- app/web_modules/sourcegraph/repo/withResolvedRepoRev.js
- app/web_modules/sourcegraph/tree/TreeActions.js
- app/web_modules/sourcegraph/tree/TreeBackend.js
- app/web_modules/sourcegraph/tree/TreeSearch.js
Before, when viewing a repository that wasn't cloned you would be asked to refresh the page: ![](http://g.recordit.co/ObQI5cj5R2.gif)
(and if you refreshed too early, code intelligence would never load until you refresh yet again).
After, the page automatically refreshes and always shows code intelligence:
In addition to the below, please confirm my JS code is on-point; nit picky review is very much appreciated!
> [DO NOT MERGE] Automatically refresh the "Cloning this repository" screen once finished.

- cli/coverage_cmd_data.go
- pkg/coverageutil/bash.go
- services/worker/plan/srclib.go
- services/worker/plan/srclib_images.go
- vendor/github.com/mkovacs/bash/LICENSE
- vendor/github.com/mkovacs/bash/scanner/scanner.go
- vendor/vendor.json
Compute coverage for `srclib-bash`.
> coverage: add bash

- services/worker/plan/srclib.go
- services/worker/plan/srclib_test.go
Currently, none of the srclib indexers are required to complete successfully for a build to be marked as successful. This change makes it so that if any of `srclib-{go,java,python,csharp}` fails AND the failing language is greater than 33% of the code in the repository, the build is marked as a failure. Marking the build as failure will also prevent the graph database from updating the graph data version, so should prevent a lot of srclib coverage regressions in production.
This fixes https://github.com/sourcegraph/srclib-python/issues/44
Tested locally.
> Mark build as failure when key language fails

- cli/coverage_cmd.go
Added `--empty` flag to display files with 0 refs, may be useful if there is a need to see pattern - what files produce no refs and what they have in common.
> Coverage: Ability to trace uncovered files

- client/browser-ext/app/analytics/EventLogger.js
- client/browser-ext/app/components/DefSearchResult.js
- client/browser-ext/app/components/SearchInput.js
- client/browser-ext/app/containers/App.js
- client/browser-ext/chrome/extension/annotations.js
- client/browser-ext/chrome/extension/inject.js
- client/browser-ext/package.json
Adds lightweight tracking to the chrome browser extension
Manually tested each event_type and reviewed each for accuracy. Also confirmed the event_properties were correct and provided relevant contextual information.
> Analytics: Chrome extension improved tracking

- services/worker/plan/srclib_images.go
rebuilt srclib-java Docker image based on sourcegraph/srclib-java@68fd56bb5cf575af7866871305e9b42c60604ad5
> updated srclib-java Docker image

- pkg/syntaxhighlight/regexp_lexer.go
- removed useless code detected by @keegancsmith and https://github.com/gordonklaus/ineffassign/
> Code cleanup

- cli/coverage_cmd_data.go
Updating the test repo for Bash coverage.
> coverage: update test repo for Bash

- vendor/sourcegraph.com/sourcegraph/srclib-java/java_def/formatter.go
- vendor/vendor.json
- fixes sourcegraph/srclib-java#73
> bumping sourcegraph.com/sourcegraph/srclib-java

- app/web_modules/sourcegraph/home/ToolComponent.js
- app/web_modules/sourcegraph/home/ToolsHomeComponent.js
- app/web_modules/sourcegraph/home/styles/Tools.css
UI fixes for SFYE. Will merge when built.
> added YouTube video to tools page

- services/backend/internal/localstore/repos.go
Before:
After:
*AUTHOR: Add other outstanding tasks for the reviewer. Remove irrelevant items below.*
> Make global repo search case insensitive

- app/web_modules/sourcegraph/app/styles/App.css
- app/web_modules/sourcegraph/app/styles/GlobalNav.css
- app/web_modules/sourcegraph/blob/styles/Blob.css
- app/web_modules/sourcegraph/components/RepoLink.js
- app/web_modules/sourcegraph/components/styles/_colors.css
- app/web_modules/sourcegraph/components/styles/breadcrumb.css
- app/web_modules/sourcegraph/components/styles/code.css
Update blob UI styles to match some improvements from latest mocks
> Blob ui updates

- app/web_modules/sourcegraph/dashboard/AnonymousLandingPage.js
- app/web_modules/sourcegraph/dashboard/styles/Home.css
- app/web_modules/sourcegraph/search/GlobalSearch.js
- Add global search to homepage
- Remove language support
- Remove some product copy
- Add search examples for Go and Java
- Make some changes to search component to allow updating live when clicking on a search link from the same page
> Search landing page

- services/backend/internal/localstore/global_refs.go
We re-use the helpers that were created for defs. They use a much better pattern
for accessing the data from postgres. I haven't been able to reliably benchmark
on my machine if this will improve performance, but the real world metrics we
are measuring heavily indicate that this will be orders of magnitude faster.
Also note that surprisingly this is by far the slowest part of global_refs
update (roughly 80% of the time taken in the p99 case).
Fixes https://app.asana.com/0/146253180133821/147371528518098
> global_refs: Use a bulk upsert / query for defKeyIDs

- app/web_modules/sourcegraph/tree/TreeSearch.js
- app/web_modules/sourcegraph/tree/fuzzy_score.js
Improve tree search: sort results by their fuzzy match score.
It's live on staging3.sourcegraph.com
> app/TreeSearch: add fuzzy scoring for search results

- services/worker/plan/srclib_images.go
This PR contains changes which should improve javascript coverage statistics for some repos - node, ...
Attempts to resolve issue after Friday major commit into srclib-javascript toolchain.
> Update srclib image

- app/web_modules/sourcegraph/components/Dropdown.js
See details: https://app.asana.com/0/87040567695724/147442522463990
cc/ @rothfels
> components/Dropdown: only bind toggle event to angle icon

- services/backend/repos.go
- services/backend/repos_test.go
We are missing metadata for lots of repositories in our DB thanks to only
unauthed users browsing them. Unauthed users will do a `Repos.Get`, which
internally will do a `Repos.Update` to sync the missing metadata. However, that
would fail since `Repos.Update` requires write permissions. Instead, it is safe
to use an elevated permission here.
Fixes https://app.asana.com/0/87040567695724/147734985562463
> repos: Use elevated perms to sync github metadata

- services/worker/plan/srclib.go
- services/worker/plan/srclib_test.go
- vendor/github.com/drone/drone-exec/parser/node.go
- vendor/github.com/drone/drone-exec/runner/utils.go
- vendor/github.com/drone/drone-exec/yaml/types.go
- vendor/vendor.json
Fixes https://app.asana.com/0/146253180133821/145711860169814
> build: Enforce specifying mem_limit for toolchains

- app/internal/ui/router.go
- app/web_modules/sourcegraph/app/routePatterns.js
- app/web_modules/sourcegraph/components/CheckboxList.js
- app/web_modules/sourcegraph/components/GitHubAuthButton.js
- app/web_modules/sourcegraph/components/index.js
- app/web_modules/sourcegraph/components/styles/checkboxList.css
- app/web_modules/sourcegraph/home/BetaInterestForm.js
- app/web_modules/sourcegraph/home/styles/BetaInterestForm.css
- app/web_modules/sourcegraph/page/BetaPage.js
- app/web_modules/sourcegraph/page/index.js
- app/web_modules/sourcegraph/user/UserActions.js
- app/web_modules/sourcegraph/user/UserBackend.js
- services/httpapi/httpapi.go
- services/httpapi/router/router.go
- services/httpapi/user.go
- Add a `CheckboxList` component for picking multiple editors / languages.
- Add new `/.api/beta-subscription` endpoint to send this form data to mailchimp.
- Note: This does not remove the old page/form/component/endpoint, and does not link to the new page, instead, this will be done as a follow-up.
--------------------------------------------
Top of page
--------------------------------------------
Bottom of page
--------------------------------------------
1.Try it out and give any feedback (you can run without a real mailchimp key and just not actually submit the data).
2. Be nit-picky about any JS/CSS/HTML errors please! I want to learn anything I can :)
All testing done manually, including ensuring that relevant data shows up in Mailchimp and is usable (shoutout to Kingy for the …
> Add the new "Beta" (register for beta access) page.

- services/backend/internal/localstore/defs.go
- services/backend/internal/localstore/defs_test.go
Quite simple change after the refactoring I did...
> search: added fulltext search of doc comments

- app/web_modules/sourcegraph/build/Build.js
- app/web_modules/sourcegraph/build/Step_test.js
- app/web_modules/sourcegraph/build/testdata/Step-failure.json
- app/web_modules/sourcegraph/build/testdata/Step-success.json
- app/web_modules/sourcegraph/build/testdata/Step-warnings.json
Fixes https://app.asana.com/0/146253180133821/150415241999794
> app: Display warnings and failed build steps to user

- client/browser-ext/app/components/App.css
Was not able to repro bug, increased zindex of popover
> increased z index of popover

- app/web_modules/sourcegraph/blob/styles/Blob.css
- app/web_modules/sourcegraph/def/AuthorList.js
- app/web_modules/sourcegraph/def/DefInfo.js
- app/web_modules/sourcegraph/def/DefPopup.js
- app/web_modules/sourcegraph/def/ExamplesContainer.js
- app/web_modules/sourcegraph/def/RefsContainer.js
- app/web_modules/sourcegraph/def/index.js
- app/web_modules/sourcegraph/def/styles/Refs.css
- app/web_modules/sourcegraph/def/testdata/DefPopup-data.json
- app/web_modules/sourcegraph/def/testdata/DefPopup-notAvailable.json
- app/web_modules/sourcegraph/delta/DiffFileList.js
- app/web_modules/sourcegraph/delta/DiffStatScale.js
- app/web_modules/sourcegraph/delta/FileDiff.js
- app/web_modules/sourcegraph/delta/FileDiffs.js
- app/web_modules/sourcegraph/delta/Hunk.js
- app/web_modules/sourcegraph/delta/styles/DiffFileList.css
- app/web_modules/sourcegraph/delta/styles/FileDiff.css
- app/web_modules/sourcegraph/delta/styles/Hunk.css
- app/web_modules/sourcegraph/delta/testdata/DiffFileList-initial.json
- app/web_modules/sourcegraph/delta/testdata/FileDiff-added.json
- app/web_modules/sourcegraph/delta/testdata/FileDiff-changed.json
- app/web_modules/sourcegraph/delta/testdata/FileDiff-deleted.json
- app/web_modules/sourcegraph/delta/testdata/FileDiff-renamed.json
- app/web_modules/sourcegraph/delta/testdata/FileDiffs-initial.json
- services/backend/vcs_util.go
These were misc. changes I encountered while going through the UI code.
> Misc changes to UI and code cleanup

- app/templates/scripts.html
- app/web_modules/sourcegraph/user/settings/UserSettingsReposMain.js
- app/web_modules/sourcegraph/util/EventLogger.js
Adds Telligent tracker - similar implementation to GA and Amplitude
> Analytics: Add Telligent tracking integration

- services/backend/internal/localstore/defs.go
- services/backend/search.go
We had some, but this completes the picture.
Fixes https://app.asana.com/0/146253180133821/152472970217590
> Instrumentation for search

- cli/coverage_cmd.go
- cli/repo_cmds.go
- cli/stress.go
- dev/sgtool/package.go
- pkg/handlerutil/handler.go
- services/backend/annotations.go
- services/backend/deltas.go
- services/backend/internal/localstore/global_refs.go
- services/backend/internal/localstore/repos.go
- services/backend/repos.go
- services/events/server.go
- test/e2e/e2etest.go
- vendor/github.com/neelance/parallel/LICENSE
- vendor/github.com/neelance/parallel/parallel.go
- vendor/vendor.json
This avoids messing up CPU and memory profiles by not adding its own stack frame.
> replace github.com/rogpeppe/rog-go/parallel with github.com/neelance/parallel

- app/web_modules/sourcegraph/app/GlobalNav.js
- app/web_modules/sourcegraph/app/styles/GlobalNav.css
- app/web_modules/sourcegraph/search/GlobalSearch.js
- app/web_modules/sourcegraph/search/SearchSettings.js
- app/web_modules/sourcegraph/user/UserStore.js
- Added support for SGDesktop. Adds Golang as default search language until new settings have been added (clicking on another language or deselecting the current language) this is to reduce one step to allow a user to search without having to overcome an initial hurdle of selecting a language
- Escape now closes the search box whenever it is pressed
- Default show of SG Desktop now automatically focuses and selects search box
- Global search container no longer consumes the entire screen on small devices 
- Added a "reset" query button when the user is searching inside of the global nav on a smaller device.
Check staging4 to see improvements and to test
> UX: Improved Global Search Experience

- services/worker/plan/srclib_images.go
Update javascript image, should include useful changes for analysing of sourcegraph/app/web_modules
> Updated srclib image

- app/web_modules/sourcegraph/def/RepoRefsContainer.js
Fixes https://app.asana.com/0/87040567695724/153142476216267
> fix bug with pagination of references

- app/web_modules/sourcegraph/def/RefsContainer.js
Fixes https://app.asana.com/0/87040567695724/153775463609634
> app: fix repeated WantFile and WantAnnotations actions

- app/web_modules/sourcegraph/dashboard/DashboardContainer.js
- app/web_modules/sourcegraph/search/GlobalSearch.js
> app: add equal vertical padding for search results notices (loading/no-results)

- services/backend/internal/localstore/db.go
Previously only 2 connections were allowed to stay idle. This caused a lot of connections to be closed and immediately reopened, which is bad for performance.
> allow DB connections to stay idle

- pkg/errcode/code.go
- pkg/store/users.go
- services/backend/internal/localstore/accounts.go
- services/backend/internal/localstore/accounts_db_test.go
This fixes the e2e test failure (e.g., https://sourcegraph.slack.com/archives/e2etest/p1468991829000143)
> pass through "account not exist" error

- app/web_modules/sourcegraph/def/withDef.js
- app/web_modules/sourcegraph/def/withDefAndRefLocations.js
Note that these won't always be 404 errors, but it's rare enough and user friendly enough that it's not a big deal. Already done the same way for repositories in RepoMain.js.
*AUTHOR: Add other outstanding tasks for the reviewer. Remove irrelevant items below.*
*AUTHOR: Describe the necessary manual test process, if any, for the reviewer to follow.*
> Update change title for errors

- app/web_modules/sourcegraph/def/DefTooltip.js
- lang/golang/cmd/langprocessor-go/Dockerfile
- lang/golang/cmd/langprocessor-go/langprocessor-go.go
- lang/golang/cmd/langserver-go/Dockerfile
- pkg/conf/feature/feature.go
- pkg/lputil/client.go
- pkg/lputil/lputil.go
- pkg/lputil/proto.go
- services/httpapi/hover_info.go
Please see individual commit messages for descriptions.
Will be enabled for all repositories, but only for staging.
> [universe] Display tooltips using LSP
