sourcegraph/sourcegraph

cmd/src/main.go, doc.go
When people see a Go package hosted on GitHub and it doesn't have a custom import path enforced via an import comment (and it doesn't say otherwise in the README), they have no better choice but to assume the import path is simply `github.com/user/repo`.
We use a vanity import path `sourcegraph.com/sourcegraph/sourcegraph/...`, and it's already partially enforced in a few places (e.g., see
https://github.com/sourcegraph/sourcegraph/blob/12f76fdffc05bd75de7beb56495e5415c2cdfc92/pkg/vcs/doc.go#L8).
Enforce and make it clear what the import path is by adding import comments to some more prominent and visible packages.
Reference: https://golang.org/cmd/go/#hdr-Import_path_checking.
Need to ensure CI passes and sourcegraph builds continue to work.
=> {,cmd/src}: Set import comment.

Makefile
The race detector has a heavy impact on the performance at runtime. It makes some tasks use many GB of RAM. Only using -race for testing now.
PS: I prefer to merge myself. ;-)
=> Makefile: use -race only for testing

app/internal/gitserver/lg_test.go, dev/circle-ci-run-tests.sh
See full commit messages.
Test plan: manually check CI logs to ensure that app/internal/gitserver's tests were run.
=> Enable gitserver tests, remove unnecessary cases

app/web_modules/sourcegraph/util/EventLogger.js
It looks like we only implemented checks for `userAgentIsBot` when calling `logEvent` to Amplitude instead of performing that check at logEvent we can set a flag up front that tells amplitude not to send the events. We also shouldn't be logging any events to intercom for e2e tests as well, but intercom looks like it doesn't have a flag for this so we will have to opt out manually. 
@slimsag could you look this over to see if this would affect the e2e tests at all?
=> Analytics: Filter out E2E and other bots from analytics based on user agent

app/web_modules/sourcegraph/channel/withChannelListener.js
I noticed that on the first pageloads from sfye, the utm source was not being listed. Digging into it, it wasn't being set in one place.
I'd love to know if there is a better way to do this URL assembly at this point, tacking on &X=A&Y=B seems error prone.
Run locally, I verified that it works by stepping through with the JS debugger.
=> fix for amplitude tracking on first sfye pageload

app/web_modules/sourcegraph/util/EventLogger.js
Setting isEmployee flag and resetting analytics opt out based on the user. It is not absolutely necessary, but if a user was marked as a bot it persists until explicitly set to false. This could be problematic when debugging analytics. For example, if you were marked as a bot while running CI and then wanted to check dev analytics at a later date to confirm everything was firing correctly it would not be immediately obvious why your user isn't firing events.
=> Analytics: Set isEmployee flag

pkg/coverageutil/csharp.go, pkg/coverageutil/csharp_test.go
Ignoring preprocessor directives in C# code when extracting identifiers to reduce number of uncovered idents in C# code (spotted by @ildarisaev)
Covered by unit test
=> Dealing with C# preprocessor directives

app/web_modules/sourcegraph/blob/BlobLine.js, app/web_modules/sourcegraph/blob/BlobMain.js, app/web_modules/sourcegraph/util/externalLink.js
- Issue:
This changes fixes a JS error which tries to react-router parse an annotation definition for external links (links outside sourcegraph domain, Eg. "https://developer.mozilla.org/en-US/docs/Web/CSS/padding"):
- Fix:
n/a
- Tested locally
=> web_modules/sourcegraph: improve external links UI support.

pkg/srclib_support/basic_formatter.go
This is needed so that Bash definitions are rendered correctly.
=> srclib_support: use basic_formatter for Bash

app/web_modules/sourcegraph/misc/golang.js
There is an Asana bug for this, but basically URLs are getting resolved as:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/info/GoPackage/github.com/sourcegraph/sourcegraph/pkg/csp/-/Policy?editor_type=sublime&utm_source=sourcegraph-editor
Instead of:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/info/GoPackage/sourcegraph.com/sourcegraph/sourcegraph/pkg/csp/-/Policy?editor_type=sublime&utm_source=sourcegraph-editor
And there are 404s using SFYE. This appears to be specific to sourecgraph.com libraries.
*AUTHOR: Add other outstanding tasks for the reviewer. Remove irrelevant items below.*
will put on a staging instance, and verifiy that SFYE works.
=> temporary fix while sourcegraph.com resolving is returning github.com

services/backend/internal/localstore/global_defs.go, services/backend/internal/localstore/repos_db_test.go
One thing missed in Quinn's [PR #26](https://github.com/sourcegraph/sourcegraph/pull/26) was the `GlobalDefs.Search` method which allows filtering by `Repos` and `NotRepos` fields. These fields were change to `int32` repo ID types, but because our `arg` SQL pattern takes `interface{}` it blindly worked without a compiler error. Thus, when you attempt to search by `Repos` `[1, 2, 3]` it compares against _repo URIs_ 1,2,3 NOT repo IDs 1,2,3 like it should.
Comparing against repo IDs requires a DB migration, which this PR does not perform. Instead, we just resolve the `Repos` and `NotRepos` repo URIs upon a call to `GlobalDefs.Search` and then run the query using repo URIs per usual. This is a stop-gap solution for a different PR I am working on, and we can switch to storing repo IDs in the …
=> services/backend/internal/localstore: fix GlobalDefs.Search with Repos / NotRepos queries

client/browser-ext/.gitignore, client/browser-ext/README.md, client/browser-ext/package.json, client/browser-ext/scripts/build-env/Dockerfile, client/browser-ext/scripts/build-env/dist.sh
"npm run build-docker" to build the docker image, then "npm run build-firefox"
firefox-build.zip should appear in the browser-ext directory.
Naming / directory structure: I created a new folder in scripts, with the stuff specific to the firefox build. Is this reasonable?
Run it on someone else's computer, does it work first try?
TODO: diff the zip file to the one created locally on the mac, and make sure they are different.
=> WIP: firefox build script takes place in docker

pkg/srclib_support/basic_formatter.go
Needed to render man page defs correctly.
=> srclib_support: use basic_formatter for man page defs

app/web_modules/sourcegraph/misc/golang.js
simple fix, it turns out that only the sourcegraph.com/sourcegraph/sourcgraph was creating invalid urls in sourcegraph for your editor. Making the corrective behavior we are taking just operate on this repo, not all sourcegraph repos.
=> sfye fix for repos hosted on sourcegraph.com

services/worker/dockerfiles/Dockerfile.srclib-bash, services/worker/plan/srclib_images.go, vendor/github.com/mkovacs/bash/scanner/scanner.go, vendor/vendor.json
Updating for changes from `srclib-bash` and `bash/scanner`.
=> srclib-bash: update deps and docker image hash

services/worker/dockerfiles/Dockerfile.srclib-java, services/worker/plan/srclib_images.go
- Docker image now contains latest Gradle 2.13
- Docker image rebuilt based on sourcegraph/srclib-java@49819eb6eec4cc8abec7d4b7a5ea0e7b58cfa0b2
Please make sure that Java projects indexing goes well after merge
=> Updating srclib-java Docker image

app/web_modules/sourcegraph/build/BuildBackend.js, cli/coverage_cmd.go, cli/repo_cmds.go, services/backend/builds.go, services/backend/mirror_repos.go, services/events/listeners/git_hooks.go, services/httpapi/repos_builds.go
We can run coverage job builds with a much lower priority such that any other
build will run first.
Fixes https://app.asana.com/0/87040567695724/140739668608789
=> builds: Ensure UI triggered/new repos have high priorities.

services/ext/github/repos.go, services/ext/github/repos_test.go
We 404 10x more than we 200 leading to our rate limit going to zero. The likely cause of this is people browsing private repositories from the Chrome Extension without them giving access to the private repo.
See commit messages.
=> github: Cache unauthed not found responses

services/ext/github/repos.go, services/ext/github/repos_test.go
Followup to #84 comments left by me. This should be a refactor that does not change behavior. These are suggestions, so @keegancsmith feel free to accept/reject them depending on if you agree.
Make `getFromCache` and `getFromAPI` signatures more traditional. They now both return (*Resource, error) where Resource can/should only be used if and only if error is nil. This behavior is also now documented.
---
Also, perform `githubutil.SplitRepoURI` first thing in github.Repos.Get, before even hitting the cache.
The cache is redis and may be a network call, etc., so the assumption is that `githubutil.SplitRepoURI` is a much cheaper/quicker operation. If the local parsing of `githubutil.SplitRepoURI` fails, there's no way it's a valid repo that would be cached.
This is a minor optimization that …
=> services/ext/github: Style changes to improve readability.

services/backend/mirror_repos.go
Fixes https://app.asana.com/0/87040567695724/140099827375686
The reason was the following: there may be multiple refnames ending with the same suffix, for example
```
$ git show-ref --heads | grep 1.0.2
...
f6c1ff038cd9ff067e344a1194cfb4c8ad194090 refs/heads/1.0.2
901b3948ffc5f4ea7ad0c5e7d68ecdeb86d4461d refs/heads/rr/146/1.0.2
...
```
then
```
$ git rev-parse 1.0.2
warning: refname '1.0.2' is ambiguous.
e5fd456075b3318eb7092ff0169a30d1298086d6
$ git rev-parse refs/heads/1.0.2
f6c1ff038cd9ff067e344a1194cfb4c8ad194090
```
When we are looking for changes, there may be false positive change detected because the results of `git show-ref` and `git rev-parse` may differ.
I propose to fix it by adding "refs/heads/" prefix because refnames there are relative to "refs/heads/" anyway
=> Corrected refname => revision resolution

services/ext/github/repos.go, services/ext/github/repos_test.go
This optimization was introduced in 7f3478a8342c2d2064f631cb0e7171be15d49715.
Caching 404 responses from authed clients is safe to do, since we're
only caching not found responses and not found repositories. This does
not reveal sensitive information.
Add test to enforce it so it doesn't regress.
Try to clear up some existing tests, explain a potentially puzzling
part of a test.
=> services/ext/github: Test that 404 responses get cached even if user is authed.

services/worker/builder/builder.go, services/worker/plan/infer.go
Example output from `Detect projects` now
```
Detected 1 programming languages in use by this repository:
- Go
Found 2 non-programming languages in use by this repository that will not be analysed:
- Markdown
- YAML
```
Before it would of been
```
Detected 3 programming languages in use by this repository:
- Go
- Markdown
- YAML
```
but then it would of warned about not being able to build all 3 languages (but
would still analyse Go).
Fixes https://app.asana.com/0/87040567695724/142418359113253
=> builds: Include Go as supported language

app/web_modules/sourcegraph/repo/styles/Repo.css, app/web_modules/sourcegraph/repo/styles/RevSwitcher.css
The ellipses truncation broke at some point (possibly after adding the RevSwitcher).
This adds back ellipses truncation and fixes text and RevSwitcher menu misalignment on mobile.
=> Fix text-ellipses and text alignment at small sizes.

cli/serve_cmd.go, cli/work_cmd.go, pkg/conf/context.go, services/worker/configure.go, services/worker/worker.go
We want to use a srclib import URL that is different to what the Meta.Config
service returns. We want this since we want imports to go through another
frontend.
=> builds: Allow worker to override AppURL

client/browser-ext/chrome/extension/annotations.js, client/browser-ext/chrome/extension/inject.js
Enabling the Chrome extension for shell scripts.
Tested locally.
=> browser-ext/chrome: enable for shell scripts

services/worker/plan/srclib_images.go
Undo revert commit 78d51f514d504f9c1b491638cf28c73ee9760c5c. This time, it's built with the right Docker version and should work.
Tested on staging3.
https://staging3.sourcegraph.com/github.com/shurcooL/play/-/builds/1
https://staging3.sourcegraph.com/github.com/shurcooL/play/-/def/GoPackage/github.com/shurcooL/play/187/tictactoe/-/Player
(Compare with https://sourcegraph.com/github.com/shurcooL/play/-/builds/8.)
Worked successfully, and indexed good Go packages despite there being bad Go packages that refer to missing repos/packages. So it also shows that fix in https://github.com/sourcegraph/srclib-go/pull/102 works.
=> services/worker/plan: Update srclib-go to incorporate sourcegraph/srclib-go#102.

services/worker/plan/srclib_images.go
Update srclib-javascript image, should contain fixes for uncommmon node_modules folder structures and improve coverage
=> Update srclib-javascript image

services/backend/internal/localstore/global_refs.go, services/backend/search.go, services/httpapi/srclib_import.go, services/httpapi/srclib_import_test.go
This minimizes the transaction zone of the global refs update step, which should hopefully improve perf.
It also forces a global_refs reindex on every successful srclib import. This will make `src repo sync -f $REPO` work as expected (previously, this wouldn't actually force a rebuild of the global_refs index, which was confusing when debugging).
=> Improve global refs update

pkg/search/search_tok.go, pkg/search/search_tok_test.go, vendor/github.com/fatih/camelcase/LICENSE.md, vendor/github.com/fatih/camelcase/README.md, vendor/github.com/fatih/camelcase/camelcase.go, vendor/vendor.json
This change tokenizes camelCased and snake_cased paths in global search results by splitting out the individual words and adding them to the bag of words representations for the results.  This improves search results, since we can now match based on parts of words in the path instead of only full words.  Right now, all separated words from camelCased and snake_cased words are given a score of 1, while an additional 10 points are given for words that are separated from the last part of the path (typically the "name" of the result).
=> Tokenize camelCase and snake_case global search results

services/backend/internal/localstore/defs_helpers.go, services/backend/internal/localstore/global_defs.go, services/backend/internal/localstore/global_refs.go
We currently don't have a good idea of what parts are slow. This adds fine-grained instrumentation all over global_refs and global_def updates.
=> Global: More instrumentation for RefreshIndexes

services/worker/dockerfiles/Makefile, services/worker/dockerfiles/README.md
This is to avoid a breaking change in docker that makes pulling images by digest fail in production, see https://docs.docker.com/engine/breaking_changes/.
=> use tags for versioning of srclib toolchain images

services/worker/configure.go
There is no information in the K8s repository to automatically derive the correct import path. This is why a manual special case is required.
=> add special case for the import path of the Kubernetes repo

app/web_modules/sourcegraph/tree/TreeSearch.js
Fix to make fuzzy search case insensitive.
See https://app.asana.com/0/135425975204116/147877634399138
Tested locally.
=> app/TreeSearch: make search case-insensitive

pkg/coverageutil/javascript.go
In construction 'import' ... 'from' ... from plays role of keyword, was not previously included in the list of javascript keywords
=> Add 'from' keyword to javascript list of keywords

app/web_modules/sourcegraph/page/AboutPage.js
This change enables `signedIn` to be set when rendering the about page. That page uses it to not display "Sign up with GitHub" buttons when the user is already signed in.
Currently, the about page always displays those because those `signedIn` is always `undefined`, no matter if the user is logged in or not:
Setting `AboutPage.contextTypes` seems to fix that. I got the idea from [the code for pricing page](https://github.com/sourcegraph/sourcegraph/blob/47f606ac15d644cc93623ffef9eb2e930b8952cd/app/web_modules/sourcegraph/page/PricingPage.js#L109-L112). However, I am not familiar with React's details enough to know if this is the best way.
I am not familiar with React's details enough to know if this is the best and most correct fix, or if the issue should be resolved in another way.
I …
=> app/web_modules: Fix ineffective signed in check on about page.

services/backend/internal/localstore/global_defs.go, services/worker/drone.go
This is my proposal how to fix https://app.asana.com/0/87040567695724/144531999537159. It includes
- trying to resolve SHA when repository contains custom default branch (for example, github.com/apache/log4j). If we were failed first time, trying to query default branch from GitHub and retry
- using updated `sourcegraph/drone-git` Docker image based on github.com/sqs/drone-git#5. Without it on my local instance I cannot start build of github.com/apache/log4j because clone fails
Please ensure that this PR does not adds too many extra calls to GitHub
=> Trying to resolve SHA of custom default branch

services/worker/dockerfiles/Makefile, services/worker/plan/srclib_test.go
In production we only support docker images which are v1. If you build an image
with docker v0.10 or higher, it breaks srclib in production. This commit adds a
test which speaks to the docker registry to ensure the image exists and is an
old enough version.
This was tested by using the image in ff1c35f6a9796e7117623848234ea96a10c4d4f3
which introduced a bad image. Also we manually modified a sha to be non-existant
to test 404.
=> builds: Prevent adding docker images prod does not support

services/backend/internal/localstore/defs.go, services/backend/search.go, services/backend/search_test.go
This fixes https://github.com/sourcegraph/sourcegraph-issues/issues/35.
Adds a unit test to the search service.
The issue before was that the srclib store `Defs.List` behavior was not as expected (it would list all definitions in the specified repository revisions, instead of fetching only the definitions that corresponded to the provided def keys). This switches the def "hydration" operation to use `Defs.Get` in parallel on all definition search results.
=> Fix non-determinism in search results

cli/internal/middleware/metric.go, services/backend/internal/middleware/inner/trace/trace.go
Also removed the heartbeat, we never use it. This should help us in future when
we have a deadlock, and also help us understand long running grpc methods
better.
=> metrics: Measure number of running grpc requests

pkg/amortize/amortize_helper.go, pkg/clock/clock.go, services/backend/auth.go, services/backend/internal/localstore/accounts.go, services/backend/internal/localstore/accounts_db_test.go, services/backend/internal/localstore/cli_config.go, services/backend/internal/localstore/password.go, services/backend/internal/localstore/password_test.go
New SQL: 
Email Tokens
```sql
ALTER TABLE password_reset_requests ADD COLUMN expires_at timestamp;
UPDATE password_reset_requests SET expires_at = now() + '4 hours';
ALTER TABLE password_reset_requests ALTER COLUMN expires_at SET NOT NULL;
```
Password Throttling
```sql
ALTER TABLE passwords ADD COLUMN consecutive_fails int;
ALTER TABLE passwords ADD COLUMN last_fail timestamp;
UPDATE passwords SET consecutive_fails = 0, last_fail = now();
ALTER TABLE passwords ALTER COLUMN last_fail SET NOT NULL;
ALTER TABLE passwords ALTER COLUMN consecutive_fails SET NOT NULL;
```
New table for storing blacklisted session tokens
Note: As this code change is the critical path it's being pushed separate from the ddl change
so it can be rolled back easily in the event of issues.
```sql
-- Session …
```
=> Grouped PR for email reset token changes and password brute-forcing changes 

dev/circle-ci-run-tests.sh, pkg/testutil/repo_helpers.go
If we have a failure it is hard to find out what it is.
Some tests also include a lot of verbose output if `-v` is specified. If we need
it, we can run the test locally.
=> ci: Remove verbose flag from go test

app/web_modules/sourcegraph/home/BetaInterestForm.js
Prior to this change the Language and Editor fields were accidentally swapped (only for the `/beta` page, which AFAIK nobody has yet signed up through /cc @uforic).
Not much, mostly sent for posterity.
Manually tested and confirmed in Mailchimp:
=> app: fix fatal flaw in Beta signup page (languages and editors fields flipped)

app/web_modules/sourcegraph/search/GlobalSearch.js, services/backend/internal/localstore/defs.go
Temporarily disabling refcount calculation in graphdb until an alternative query that doesn't perform such a large scan.  See https://app.asana.com/0/87040567695724/150990295471745 for more info.
=> Hotfix for graphdb update refcount slowdown

test/e2e/e2etest.go
This makes all those errors in the log of the selenium-server container go away.
=> don't run e2e tests in parallel because it causes errors with Selenium

services/worker/plan/srclib.go
If more than a 1/3 of a repo is JS, we will mark the build as failed if the JS
step fails.
Fixes https://app.asana.com/0/146253180133821/150415241999794
=> builds: Add JS to must succeed list

app/web_modules/sourcegraph/components/styles/dropdown.css
Previously: 
Now:
@chexee , mind taking a look? I checked in our code base, and I don't see the <Dropdown used anywhere else except this instance in DefInfo. 
Also, @chexee , if vertical-align isn't specified, this fixes it as well. maybe cleaner than forcing it?
Tested locally, and is fixed. Checked if anyone else uses Dropdown.css, and couldn't find any users.
=> change vertical align for dropdown to realign translate button

services/backend/internal/localstore/repos.go
Small change to swallow errors that would indicate that a valid repo exists at a URL, preventing repo enumeration attacks.  We simply always return a 404 externally in the case of 404 or 401 Unauthorized.
=> Prevent unauthorized repo api access from leaking info. 401 -> 404

services/backend/internal/localstore/defs.go, services/backend/internal/localstore/defs_test.go
This is to fix the "string is too long for tsvector" error (and not waste performance).
=> limit word combinations for fulltext search to first 6 words

app/web_modules/sourcegraph/util/EventLogger.js
Adds a platform for analytics calls that matches Platform for ChromeExtension. This also means event properties can be Web, Chrome ext, integration and also pass in additional props that let us know how the integration was kicked off i.e Platform: Desktop that came from Sublime.
=> Add platform to event properties

test/e2e/def_flow.go, test/e2e/register_flow.go, test/e2e/search_flow.go
This change ensures that the first result for every Go query on the Sourcegraph.com has valid usage examples and does not 404. 
*AUTHOR: Describe the necessary manual test process, if any, for the reviewer to follow.*
Ensure selenium is running per `README.md` in testing folder. 
Run `SELENIUM_SERVER_IP=localhost TARGET=https://sourcegraph.com TARGET_GRPC=https://grpc.sourcegraph.com go test -run TestSearchFlow` and ensure end to end test performs function as advertised
=> better e2e testing for search

app/web_modules/sourcegraph/app/appdash.js
The DOM may have not fully loaded, which leads to `domComplete=0`. ie we show
`-unixtime` as the duration. Instead we can just rely on the current time.
Fixes https://app.asana.com/0/87040567695724/151870203669931
=> ui: Use correct duration in appdash initial load

services/httpapi/internal_appdash.go, services/repoupdater/repo_updater.go
This is unfortunetly an easy mistake to make since we have no tools to prevent it, nor to warn when it is happening in production (yet). This is currently causing prometheus to fail at collecting important frontend metrics.
=> Remove bad metrics from prometheus

app/web_modules/sourcegraph/app/GlobalNav.js
Explicitly hides the search results box after a result is selected by setting open to false after `state.nextQuery` is set to null.
This is on staging4
=> UX: Hide search box after result is selected

app/web_modules/sourcegraph/app/GlobalNav.js
Fixes this bug: https://cl.ly/3v1q1I2K2l2m, where pressing enter on an empty search when on a repo page changes the search scope to global and takes you away from the repo. 
*AUTHOR: Add other outstanding tasks for the reviewer. Remove irrelevant items below.*
^^ Is there a reason the `updatePath` param was set to `true` previously?
=> Fix location change on search submit

app/web_modules/sourcegraph/components/Icons.js, app/web_modules/sourcegraph/def/ExamplesContainer.js, app/web_modules/sourcegraph/def/RefsContainer.js, app/web_modules/sourcegraph/def/RefsContainer_test.js, app/web_modules/sourcegraph/def/styles/Refs.css, app/web_modules/sourcegraph/user/index.js, app/web_modules/sourcegraph/util/constants/AnalyticsConstants.js
This change adds simple upvote/downvote buttons for admin users which directly
submit data to Amplitude including four identifying datapoints:
1. Whether it was an upvote or a downvote.
2. Which page (`window.location.href`) the user was on.
3. Which repository the usage example definition comes from.
4. Which file the usage example definition comes from.
5. Which index the usage example has (zero-based number which shows us where on
the page the usage example was located, not good for concretely identifying
the usage example hence the repo/file fields above).
When the upvote/downvote button is clicked, we simply fade out the buttons.
Tested manually.
=> app: display upvote/downvote buttons on Usage Examples for admin users

test/e2e/def_flow.go, test/e2e/e2etest.go, test/e2e/login_flow.go, test/e2e/register_flow.go, test/e2e/search_flow.go
We add the convenience function so that we can add a work-around on an issue
that affects ChromeDriver. Our assumption is that ChromeDriver will try to click
on an element, but between the time it gets the element and clicks on it, the
element moves. This happens a lot on the Usage Examples page, since we
asynchronously load in some extra annotations that appear above the `View all
references` button. This lead to internal errors from selenium, with selenium
logs like the following:
```
org.openqa.selenium.WebDriverException: unknown error:
Element is not clickable at point (810, 295).
Other element would receive the click: <div class="Blob__margin___2uZsC" style="position: relative;">...</div>
```
More information at https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/ …
=> e2e: Add convenience function Click

pkg/httputil/cache.go, pkg/rcache/rcache.go, pkg/rcache/rcache_test.go
Previously we used an in-memory cache for caching at the HTTP Transport
layer in the Github Client. This lead to large amount of uncached requests
to the Github API on startup (eg when deploying). This started to cause us
to get uncomfortably close to getting rate limited to no requests.
This change switches us from an in-memory cache to Redis. This will also
have the advantage of all instances sharing the same cache, further
reducing the hits we do against the GitHub API. A new type of Redis cache
is introduced called
`rcache.ByteCache` which matches the interface used by `httpcache`.
Note that `httputil.Cache` and `httputil.CachingClient` is currently only
used by GitHub.
Fixes https://app.asana.com/0/87040567695724/154090028181702
=> github: Use an HTTP cache backed by Redis

pkg/httputil/cache.go, pkg/rcache/rcache.go, pkg/rcache/rcache_test.go, services/ext/github/repos.go, services/ext/github/repos_test.go
This is a follow-up to https://github.com/sourcegraph/sourcegraph/pull/261
We greatly simplify the implementation and uses of the API. There are plenty of commits, but they are all small and do one thing. Easiest way to review is each commit independently.
=> rcache: Simplify implementation

app/web_modules/sourcegraph/home/index.js, app/web_modules/sourcegraph/page/index.js, app/web_modules/sourcegraph/user/settings/routes.js
Added `navContext: null` for `home` routes, `page` routes, and `settings` routes.
=> Fix for stuck repository breadcrumb 

app/web_modules/sourcegraph/dashboard/DashboardContainer.js
Without setting signedIn on the state, the sourcegraph/Component class
would return shouldComponentUpdate == false when this.context.signedIn
changed, because it wasn't reflected in state. The contract of
sourcegraph/Component states that the state must entirely reflect the
values that need to cause rerenders.
Fixes https://app.asana.com/0/87040567695724/154969378440945
=> app: rerender DashboardContainer when context.signedIn changes

app/web_modules/sourcegraph/def/RefsContainer.js, app/web_modules/sourcegraph/def/RefsContainer_test.js
Previously the code was iterating over the list of definition results and issuing a WantFile and WantAnnotations for each of them, although they may all be in a few or even a single file. This means that the actions were issued multiple times for the same file. The new implementation iterates over the list of files instead.
Fixes https://app.asana.com/0/87040567695724/153775463609634
=> app: fix repeated WantFile and WantAnnotations actions (second try)

app/web_modules/sourcegraph/dashboard/DashboardContainer.js
Right now in prod, double clicking on any search example causes garbage text to be entered into the search box (although the correct term is still searched). 
You can see an example of this here: https://cl.ly/1J2j3122192v
Now, I've added checks that prevents more than one example from being typed at any given time. 
Example here: https://cl.ly/2b3u1I292v0Z
=> fixed rapid click behavior when clicking on top search examples

app/web_modules/sourcegraph/dashboard/DashboardContainer.js, app/web_modules/sourcegraph/def/RefsContainer.js, app/web_modules/sourcegraph/def/styles/Refs.css
Previously, the "Used in REPO" link just linked to the repo homepage, which
was not very helpful.
This change makes it so that it now says "From REPO" and it links to the file
and line number that the ref came from. This is not perfect, but it's a big
improvement.
=> app: link to the line of the ref when viewing an example

test/e2e/e2etest.go, test/e2e/e2etest_test.go
This change effectively sends failure alerts (if any test has failed) top OpsGenie (only one alert will be created).
Additionally, a few minor bug fixes which make working with e2etest locally are also included.
Tested manually. I will deploy directly to prod once merged.
=> e2etest: send failure alerts to OpsGenie + minor fixes

services/backend/internal/localstore/defs.go
This has lead to all search results for `github.com/golang/go` disappearing. The
theory of why is a few possibilities:
* Flakiness from srclib-store
* Bad import
* Race condition between importing and new commits
* Race condition in how we gc old data (there can be concurrent updates for a
repo)
This commit should guard against all of those points expept the last. Another
commit will address that issue.
Note: It may be completely valid for a repo to have no exported symbols. In such
case we will just record the error on the async queue, but the error won't have
any other effect on the user.
=> search: Ensure we have defs when indexing a commit

app/web_modules/sourcegraph/user/UserBackend.js
Change the redirect URL after logout from `/` to `/#logout` so the desktop app can detect it.
Also redirect to `/` after login to clear any leftover `#logout` from a previous logout which would look confusing.
Tested locally. Deploying to `staging3`...
=> Rig logout so the desktop app can detect it by looking at the URL

lang/sample/README.md, lang/sample/sample_server.go, lang/vscode-client/.gitignore, lang/vscode-client/.vscode/launch.json, lang/vscode-client/.vscode/settings.json, lang/vscode-client/.vscode/tasks.json, lang/vscode-client/.vscodeignore, lang/vscode-client/License.txt, lang/vscode-client/README.md, lang/vscode-client/ThirdPartyNotices.txt, lang/vscode-client/package.json, lang/vscode-client/src/extension.ts, lang/vscode-client/test/index.ts, lang/vscode-client/tsconfig.json, lang/vscode-client/typings/node.d.ts, lang/vscode-client/typings/vscode-typings.d.ts, pkg/jsonrpc2/jsonrpc2.go, pkg/jsonrpc2/jsonrpc2_test.go, pkg/jsonrpc2/logging.go, pkg/lsp/jsonrpc.go, pkg/lsp/service.go, pkg/lsp/structures.go
This change adds support for language servers.  In this change is a JSON-RPC implementation in `pkg/jsonrpc2`, language server protocol types in `pkg/lsp`, and a sample language server and Visual Studio Code extension for using the language server in `lang/server` and `lang/vscode-client` respectively.
=> Language server support

.gitignore, lang/golang/cmd/langprocessor-go/Dockerfile, lang/golang/cmd/langprocessor-go/build.sh, lang/golang/cmd/langprocessor-go/langprocessor-go.go, pkg/lputil/lputil.go, pkg/lputil/proto.go
This change adds a langprocessor-go binary which implements the intermediate Language Processor REST protocol (via the new `pkg/lputil`). It simply translates from LSP into the REST protocol in an effort to serve hover requests.
It can be tested via:
```
curl -H "Content-Type: application/json" -X POST -d '{"Repo": "github.com/gorilla/mux", "Commit": "d391bea3118c9fc17a88d62c9189bb791255e0ef", "File": "mux.go", "Line": 17, "Character": 5}' http://localhost:4141/hover
```
After starting it:
```
go install ./lang/golang/cmd/langprocessor-go/ && langprocessor-go
```
And the LSP server which it connects to:
```
go install ./lang/golang/cmd/langserver-go/ && langserver-go
```
Which ultimately produces the response:
```
{"Contents":[{"Type":"","Value":""},{"Type":"go","Value":"func …
```
=> {lang/golang, pkg/lputil}: add langprocessor-go which implements the intermediate REST protocol

services/backend/internal/middleware/inner/gen_middleware.go, services/backend/internal/middleware/inner/inner_middleware.go
Viewing logs at the moment is not very useful since nearly everything is
sanitized. This modifies are behaviour such that we still return sanitized
errors, but we log the real error to aid debugging.
=> grpc: Log unsanitized error

cli/git_server_cmd.go, cli/serve_cmd.go, lang/golang/cmd/langprocessor-go/langprocessor-go.go, lang/golang/cmd/langserver-go/langserver-go.go, pkg/debugserver/debug.go
Factored out the code we use in `src serve` so we can re-use it.
=> golang: Add debug HTTP endpoints to cmds
